version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  miniofaas:
    lang: node10-express
    handler: ./miniofaas
    image: chetinchog/miniofaas:latest
    environment:
      write_debug: true
